[backport][develop-0.1] fix(github/workflows/release): increase chances of successful pushing of source branch (#2193)
fix(github/workflows/release): increase chances of successful pushing of source branch (#2187)

this mitigates an issue that occurred in the [most recent release][0].

```
Run set -xeu
  set -xeu
  git push origin ${HOLOCHAIN_SOURCE_BRANCH}
  shell: /usr/bin/bash -e {0}
  env:
    HOLOCHAIN_REPO: /var/tmp/holochain_repo
    CACHIX_REV: v1.2
    HOLOCHAIN_SOURCE_BRANCH: develop
+ git push origin develop
To https://github.com/holochain/holochain
 ! [rejected]        develop -> develop (fetch first)
error: failed to push some refs to 'https://github.com/holochain/holochain'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Error: Process completed with exit code 1.
```

0: https://github.com/holochain/holochain/actions/runs/4613614540/jobs/8166379124#step:13:1