More thorough tests for sys validation (#2215)
* Add some notes about what to test next

* Use contrafact to build valid chain

* Add CascadeSource to differentiate local and network data

* WIP

* use Cascade trait for sys validation

* Use cascade trait for app validate_op

* Construct mock cascade with hardcoded records

* Basic test of mock cascade

* WIP, rewrite existing sys val tests to use full function

* Still working on generating valid data

* record_with_mock_cascade finally works

* WIP

* WIP

* update source 'rust-overlay' on branch 'develop' (#2184)

[create-pull-request] automated change

Co-authored-by: steveeJ <steveeJ@users.noreply.github.com>

* Fix bug with get dependants filtered caching its filter (#2155)

* Fix bug with get dependants filtered caching its filter

* minimize tests for 'Fix bug with get dependants filtered caching its filter' (#2177)

Co-authored-by: ThetaSinner <greatdjonfire@hotmail.co.uk>

* fixup: brings back a mistakenly removed test (#2178)

fixup! minimize tests for 'Fix bug with get dependants filtered caching its filter'

brings back a mistakenly removed test

* Trigger CI

---------

Co-authored-by: Stefan Junker <1181362+steveeJ@users.noreply.github.com>

* feat(github/workflows): run PR tests from within release.yml (#2175)

this lets use the 'github-actions-ci-jobs-succeed' to determine success
of PR tests.

* create a release from branch release-20230405.003224

the following crates are part of this release:

- holo_hash-0.2.0-beta-rc.2
- holochain_integrity_types-0.2.0-beta-rc.2
- hdk_derive-0.2.0-beta-rc.2
- hdi-0.3.0-beta-rc.2
- holochain_zome_types-0.2.0-beta-rc.2
- hdk-0.2.0-beta-rc.2
- kitsune_p2p-0.2.0-beta-rc.2
- holochain_sqlite-0.2.0-beta-rc.2
- holochain_keystore-0.2.0-beta-rc.2
- holochain_types-0.2.0-beta-rc.2
- holochain_p2p-0.2.0-beta-rc.2
- holochain_state-0.2.0-beta-rc.2
- holochain_cascade-0.2.0-beta-rc.2
- holochain_wasm_test_utils-0.2.0-beta-rc.2
- holochain_conductor_api-0.2.0-beta-rc.2
- holochain_test_wasm_common-0.2.0-beta-rc.2
- holochain-0.2.0-beta-rc.2
- holochain_cli_bundle-0.2.0-beta-rc.1
- holochain_cli_sandbox-0.2.0-beta-rc.1
- holochain_cli-0.2.0-beta-rc.2

* 2023 03 20 node id kitsune (#2113)

* wip on block

* host_fn compiling

* fmt

* sketch block

* hook up (un)block to conductor

* hookup block in conductor

* to sql for blockg

* wip on block span

* db queries for (un)block

* wip on is blocked

* block tests

* more block tests

* remove lossy timestamp in sql

* lint

* tests for block

* more block tests

* wip on block validity

* more tests for block

* test

* micros for column name in block

* lint

* migration for block

* docs

* Update crates/holochain_zome_types/src/block.rs

Co-authored-by: David Braden <neonphog@gmail.com>

* fix migration

* wip on kitsune types

* wip on kitsune block types

* move block span to new schema file

* lint

* fix block sql

* kitsune api

* full kitsune api access to blocks

* block rejected validation receipts 4eva

* enforce blocks on remote call

* fix build

* test for zome call blocking

* fix tests

* add node id to tx5 block

* node id on connect for tx2

* block more networking

* fix builds

* fmt

* move kitsune disconnect

* is authorized kitsune

* nodespace block

* lint

* lint

* test utils

* fix static checks

* debug

* db read for is blocked

---------

Co-authored-by: David Braden <neonphog@gmail.com>

* update source 'nixpkgs' on branch 'develop' (#2190)

[create-pull-request] automated change

Co-authored-by: steveeJ <steveeJ@users.noreply.github.com>

* update source 'rust-overlay' on branch 'develop' (#2192)

[create-pull-request] automated change

Co-authored-by: steveeJ <steveeJ@users.noreply.github.com>

* fix(github/workflows/release): increase chances of successful pushing of source branch (#2187)

this mitigates an issue that occurred in the [most recent release][0].

```
Run set -xeu
  set -xeu
  git push origin ${HOLOCHAIN_SOURCE_BRANCH}
  shell: /usr/bin/bash -e {0}
  env:
    HOLOCHAIN_REPO: /var/tmp/holochain_repo
    CACHIX_REV: v1.2
    HOLOCHAIN_SOURCE_BRANCH: develop
+ git push origin develop
To https://github.com/holochain/holochain
 ! [rejected]        develop -> develop (fetch first)
error: failed to push some refs to 'https://github.com/holochain/holochain'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Error: Process completed with exit code 1.
```

0: https://github.com/holochain/holochain/actions/runs/4613614540/jobs/8166379124#step:13:1

* Make manifests easier to use (#2138)

* Make manifest schemas easier to consume

* Format changed files

* Add back the readme in the right place

* Update hApp schema following version->installed_hash change

* Add app storage info request (#2147)

* Add storage info request

* Add a test for getting storage info for an app

* Add a test for getting storage info for all apps

* Describe storage info api in the changelog

* Support getting the size of the cache db too

* Rework storage info following the discussion on #1660

* Update changelogs

* Fix clippy warning

* Rename blobs to include DNA information

* Fix compile error from rebase

* Rewrite some more tests to use full Records

* Entry size validation, converted more tests

* Test of entry size validation

* Update check_update_reference_test

* Add ArbitraryExt trait and use it

* Update link tag size test

* Move check_entry_def to app validation workflow

* Fix warnings

* Fix errors

* Fix consistency error header

* WIP check_entry_visibility

* Use RecordEntry in DhtOp

* Clippy

* WIP of some kind

* Update for contrafact 0.1.0

* Fix action and entry match test

* Fix test

* Cargo update

* Cargo update other crates

* More fixes

* test_record_with_cascade consistently passes

* Clippy

* Bump contrafact

* Disable contrafact patch

* fmt

* Changelog

* Clippy

* More clippy

* update source 'rust-overlay' on branch 'develop' (#2483)

[create-pull-request] automated change

Co-authored-by: steveeJ <steveeJ@users.noreply.github.com>

* update source 'nixpkgs' on branch 'develop' (#2485)

[create-pull-request] automated change

Co-authored-by: steveeJ <steveeJ@users.noreply.github.com>

* Update 0_1 to 0.1.5 (#2482)

* Flamegraph in memory (#2450)

* WIP Run flame in memory

* reduce memory usage

* Clean up testing

* Format

* Clippy fix

* Keep previous code

* Format

* update source 'rust-overlay' on branch 'develop' (#2487)

[create-pull-request] automated change

Co-authored-by: steveeJ <steveeJ@users.noreply.github.com>

* update source 'nixpkgs' on branch 'develop' (#2488)

[create-pull-request] automated change

Co-authored-by: steveeJ <steveeJ@users.noreply.github.com>

* update source 'versions/0_1' on branch 'develop' (#2489)

chore(flakes): update ./versions/0_1

Co-authored-by: Holochain Release Automation <hrabot@holochain.org>

* Use new contrafact with generators

* update source 'nixpkgs' on branch 'develop' (#2490)

[create-pull-request] automated change

Co-authored-by: steveeJ <steveeJ@users.noreply.github.com>

* update source 'rust-overlay' on branch 'develop' (#2491)

[create-pull-request] automated change

Co-authored-by: steveeJ <steveeJ@users.noreply.github.com>

* Fix valid_chain_fact_test (TODO: integrate with non-contrafact test)

* update source 'rust-overlay' on branch 'develop' (#2492)

[create-pull-request] automated change

Co-authored-by: steveeJ <steveeJ@users.noreply.github.com>

* update source 'nixpkgs' on branch 'develop' (#2494)

[create-pull-request] automated change

Co-authored-by: steveeJ <steveeJ@users.noreply.github.com>

* update source 'versions/0_1' on branch 'develop' (#2495)

chore(flakes): update ./versions/0_1

Co-authored-by: Holochain Release Automation <hrabot@holochain.org>

* Remove local path

* update source 'rust-overlay' on branch 'develop' (#2496)

[create-pull-request] automated change

Co-authored-by: steveeJ <steveeJ@users.noreply.github.com>

* create a release from branch release-20230614.004108

the following crates are part of this release:

- holochain_trace-0.3.0-beta-dev.1
- kitsune_p2p_dht_arc-0.3.0-beta-dev.2
- holo_hash-0.3.0-beta-dev.3
- holochain_integrity_types-0.3.0-beta-dev.3
- hdk_derive-0.3.0-beta-dev.3
- hdi-0.4.0-beta-dev.3
- kitsune_p2p_bin_data-0.3.0-beta-dev.3
- kitsune_p2p_block-0.3.0-beta-dev.3
- kitsune_p2p_dht-0.3.0-beta-dev.2
- holochain_zome_types-0.3.0-beta-dev.3
- hdk-0.3.0-beta-dev.4
- kitsune_p2p_types-0.3.0-beta-dev.3
- holochain_keystore-0.3.0-beta-dev.3
- kitsune_p2p_fetch-0.3.0-beta-dev.3
- kitsune_p2p_transport_quic-0.3.0-beta-dev.3
- kitsune_p2p_proxy-0.3.0-beta-dev.3
- kitsune_p2p-0.3.0-beta-dev.3
- holochain_sqlite-0.3.0-beta-dev.3
- holochain_types-0.3.0-beta-dev.3
- kitsune_p2p_bootstrap-0.2.0-beta-dev.3
- holochain_p2p-0.3.0-beta-dev.3
- holochain_state-0.3.0-beta-dev.3
- holochain_cascade-0.3.0-beta-dev.4
- holochain_wasm_test_utils-0.3.0-beta-dev.3
- holochain_conductor_api-0.3.0-beta-dev.4
- holochain_test_wasm_common-0.3.0-beta-dev.4
- holochain_websocket-0.3.0-beta-dev.1
- holochain-0.3.0-beta-dev.4
- holochain_cli_bundle-0.3.0-beta-dev.3
- holochain_cli_run_local_services-0.3.0-beta-dev.3
- holochain_cli_sandbox-0.3.0-beta-dev.4
- holochain_cli-0.3.0-beta-dev.4

* update source 'rust-overlay' on branch 'develop' (#2499)

[create-pull-request] automated change

Co-authored-by: steveeJ <steveeJ@users.noreply.github.com>

* wip on dna info 2 (#2366)

* wip on dna info 2

* wip on callback versioning

* wip on v2 self check

* v2 of genesis self check

* map genesis self check in map extern

* wip on fixing tests

* fix tests

* docs for versoning

* test dna_info_1

* genesis_self_check_1 test

* legacy check

* test that dna info is callable in genesis self check

* agent key in genesis self check 2

* fix tests

* changelog

* update source 'nixpkgs' on branch 'develop' (#2500)

[create-pull-request] automated change

Co-authored-by: steveeJ <steveeJ@users.noreply.github.com>

* update source 'rust-overlay' on branch 'develop' (#2501)

[create-pull-request] automated change

Co-authored-by: steveeJ <steveeJ@users.noreply.github.com>

* Update crates/holochain_integrity_types/src/record.rs

Co-authored-by: Jost Schulte <jost.schulte@protonmail.com>

---------

Co-authored-by: Holochain Release Automation <100725712+holochain-release-automation2@users.noreply.github.com>
Co-authored-by: steveeJ <steveeJ@users.noreply.github.com>
Co-authored-by: ThetaSinner <ThetaSinner@users.noreply.github.com>
Co-authored-by: Stefan Junker <1181362+steveeJ@users.noreply.github.com>
Co-authored-by: Holochain Core Dev Team <devcore@holochain.org>
Co-authored-by: David Meister <thedavidmeister@gmail.com>
Co-authored-by: David Braden <neonphog@gmail.com>
Co-authored-by: Holochain Release Automation <hrabot@holochain.org>
Co-authored-by: Jost Schulte <jost.schulte@protonmail.com>